= Flight Contest maps server
Thomas Weise, Deutscher Präzisionsflug-Verein e.V.
:revnumber: 3.2.M23
:revdate:   11.12.2021
:nofooter:
:toc-title: Table of content
:toc:
:lang: en

[[introduction]]
== Introduction

Setting up a Flight Contest maps server.

Descriptions and tools based on following projects

* Printmaps (http://printmaps-osm.de, https://github.com/printmaps/printmaps)
* OpenTopoMap (https://github.com/der-stefan/OpenTopoMap) 

[[server-requirements]]
== Virtual server requirements
* RAM: 32GB (not dynamic)
* SSD: 1024GB
* CPU: 16
* OS: Ubuntu 18.04 LTS 64bit

such as: Strato V-Server Linux V80

[[software-installation]]
== Software installation

SSH login with user *root*

 ssh -l root <server-dns-name>

If first login, change password with ```passwd```


=== Install Ubuntu updates

 apt update
 apt upgrade
 
If something has been installed run

 sync;sync;shutdown -r now

=== Install tools, libraries and fonts

 apt-get install nano git-core cmake
 apt-get install zip unzip tar wget bzip2 mc
 apt-get install libboost-all-dev build-essential autoconf libtool
 apt-get install libosmium2-dev libprotozero-dev rapidjson-dev libboost-program-options-dev 
 apt-get install zlib1g-dev libexpat1-dev pandoc
 apt-get install libxml2-dev libgeos-dev libgeos++-dev libpq-dev libbz2-dev libproj-dev
 apt-get install munin-node munin libprotobuf-c0-dev protobuf-c-compiler libfreetype6-dev
 apt-get install libtiff5-dev libicu-dev libgdal-dev libcairo-dev libcairomm-1.0-dev libagg-dev
 apt-get install devscripts libjson-perl libipc-sharelite-perl libgd-perl debhelper
 apt-get install liblua5.2-dev lua5.1 liblua5.1-dev lua5.3 liblua5.3-dev
 apt-get install ttf-unifont fonts-noto
 
=== Install *Postgres* database server

 apt-get install postgresql postgresql-contrib postgis
 
 nano /etc/postgresql/10/main/postgresql.conf

In nano you can search with ```Ctrl-w```. +
Check or edit the following values

 shared_buffers = 128MB
 work_mem = 256MB			
 maintenance_work_mem = 256MB
 autovacuum = off

Save with ```Ctrl-x``` then ```y``` then ```Enter```

 nano /etc/sysctl.conf

At the top, after the other kernel-definitions, insert the following and save it

 kernel.shmmax=268435456

Restart server

 sync;sync;shutdown -r now
 
Check successfully restart

 who -b
 
=== Install *Mapnik* renderer

 apt-get install libmapnik3.0 libmapnik-dev mapnik-utils python-mapnik unifont

=== Compile and install *osm2pgsql*

 mkdir ~/src
 cd ~/src
 git clone git://github.com/openstreetmap/osm2pgsql.git
 
 cd osm2pgsql
 mkdir build && cd build
 cmake ..
 make
 make install

=== Install *Osmium*

 apt-get install osmium-tool
 
=== Configure *Python 3* as default

 nano ~/.bashrc

Insert the following at the bottom and save it

 alias python=python3

Then

 source ~/.bashrc

Check Python version with

 python --version

=== Install *phyghtmap*

 apt-get install python3-setuptools python3-matplotlib python3-bs4 python3-numpy python3-gdal
 
 cd ~/src
 wget http://katze.tfiu.de/projects/phyghtmap/phyghtmap_2.10.orig.tar.gz
 tar -xvzf phyghtmap_2.10.orig.tar.gz
 cd phyghtmap-2.10
 python3 setup.py install

=== Install *gdal*

 apt-get install gdal-bin python-gdal

=== Configure users and roles

Create user *gis* with group *gis* and directory */home/gis*.

 adduser gis

Add role *gis* to Postgres database server

 sudo -u postgres -i
 createuser --createdb gis -s
 exit

[[create-data]]
== Create data

SSH login with user *gis*

 ssh -l gis <server-dns-name>

Start screen

 screen

You may close SSH console while command is running. After new SSH login continue with

 screen -r

Close ```screen``` with 

 exit
 
=== Create data folder

 cd ~
 mkdir data

=== Download and install Flight Contest maps server
 
 cd ~/data
 wget http://download.flightcontest.de/fcmaps.zip
 cd ~
 unzip ~/data/fcmaps.zip

=== Download and install water polygons

 cd ~/data
 wget https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip
 wget http://download.flightcontest.de/water-polygons-generalized-3857.zip
 
 cd ~/fcmaps/otm/mapnik
 mkdir data
 cd ~/fcmaps/otm/mapnik/data
 unzip ~/data/water-polygons-split-3857.zip
 unzip ~/data/water-polygons-generalized-3857.zip

 cd ~/fcmaps/otm-dev/mapnik
 ln -s ~/fcmaps/otm/mapnik/data .
 
=== OSM data

Data upgrade: Remove databases *gis* and *lowzoom*

 dropdb gis
 dropdb lowzoom
 
Create database *gis*

 createdb gis
 psql -d gis -c 'CREATE EXTENSION postgis;'

Download data for necessary countries (Germany, Austria, Switzerland, France, South Africa: 4GB)

 cd ~/data
 mkdir osm && cd osm
 wget http://download.geofabrik.de/europe/germany-latest.osm.pbf
 cd ~/data
 mkdir osm2 && cd osm2
 wget http://download.geofabrik.de/europe/austria-latest.osm.pbf
 wget http://download.geofabrik.de/europe/switzerland-latest.osm.pbf
 wget http://download.geofabrik.de/europe/france-latest.osm.pbf
 wget http://download.geofabrik.de/africa/south-africa-latest.osm.pbf

Load OSM data into OSM database (~/data/osm/*.pbf -> gis)

 cd ~
 osm2pgsql -d gis --slim --cache 12000 --number-processes 10 --style ~/fcmaps/osm2pgsql/fcmaps.style ~/data/osm/germany-latest.osm.pbf

Wait... (8h)

 for pbffile in ~/data/osm2/*.pbf; do osm2pgsql -d gis --append --slim --cache 12000 --number-processes 10 --style ~/fcmaps/osm2pgsql/fcmaps.style $pbffile; done
 
Wait... (22h) 

Compile preprocessing tools (warnings can be ignored)

 cd ~/fcmaps/otm/mapnik/tools/
 cc -o saddledirection saddledirection.c -lm -lgdal
 cc -Wall -o isolation isolation.c -lgdal -lm -O2
 ls -l
 
Preprocessing

 cd ~/fcmaps/otm/mapnik/tools/
 psql gis < arealabel.sql
 bash update_lowzoom.sh

Wait... (1h)

 bash update_saddles.sh

Wait... (10min)

 bash update_isolations.sh

Wait... (5min)
 
 psql gis < stationdirection.sql
 
Wait... (15min)

 psql gis < viewpointdirection.sql
 psql gis < pitchicon.sql

=== Contour data

Create database *contours*
 
 createdb contours
 psql -d contours -c 'CREATE EXTENSION postgis;'
 
Download all necessary SRTM tiles, see http://www.viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm

 cd ~/data
 mkdir srtm
 cd ~/data/srtm
 nano list.txt

Insert the following (for Germany, Austria, Switzerland, South Africa)

 http://viewfinderpanoramas.org/dem3/L31.zip
 http://viewfinderpanoramas.org/dem3/L32.zip
 http://viewfinderpanoramas.org/dem3/L33.zip
 http://viewfinderpanoramas.org/dem3/L34.zip
 http://viewfinderpanoramas.org/dem3/M31.zip
 http://viewfinderpanoramas.org/dem3/M32.zip
 http://viewfinderpanoramas.org/dem3/M33.zip
 http://viewfinderpanoramas.org/dem3/M34.zip
 http://viewfinderpanoramas.org/dem3/N31.zip
 http://viewfinderpanoramas.org/dem3/N32.zip
 http://viewfinderpanoramas.org/dem3/N33.zip
 http://viewfinderpanoramas.org/dem3/N34.zip
 http://viewfinderpanoramas.org/dem3/SG33.zip
 http://viewfinderpanoramas.org/dem3/SG34.zip
 http://viewfinderpanoramas.org/dem3/SG35.zip
 http://viewfinderpanoramas.org/dem3/SG36.zip
 http://viewfinderpanoramas.org/dem3/SH33.zip
 http://viewfinderpanoramas.org/dem3/SH34.zip
 http://viewfinderpanoramas.org/dem3/SH35.zip
 http://viewfinderpanoramas.org/dem3/SH36.zip
 http://viewfinderpanoramas.org/dem3/SI33.zip
 http://viewfinderpanoramas.org/dem3/SI34.zip
 http://viewfinderpanoramas.org/dem3/SI35.zip

Save it and continue with

 wget -i list.txt

Move zip files to region folder and unpack all

 mkdir europe && mv N*.zip europe && mv M*.zip europe && mv L*.zip europe
 mkdir africa && mv S*.zip africa
 for zipfile in europe/*.zip; do unzip -j -o "$zipfile" -d europe/unpacked; done
 for zipfile in africa/*.zip; do unzip -j -o "$zipfile" -d africa/unpacked; done
 
Fill all voids per region (*.hgt -> *.hgt.tif)

 for hgtfile in europe/unpacked/*.hgt; do gdal_fillnodata.py $hgtfile $hgtfile.tif; done
 for hgtfile in africa/unpacked/*.hgt; do gdal_fillnodata.py $hgtfile $hgtfile.tif; done

Merge into one huge tif per region (*.hgt.tif -> raw.tif)

 gdal_merge.py -n 32767 -co BIGTIFF=YES -co TILED=YES -co COMPRESS=LZW -co PREDICTOR=2 -o europe/unpacked/raw.tif europe/unpacked/*.hgt.tif

 gdal_merge.py -n 32767 -co BIGTIFF=YES -co TILED=YES -co COMPRESS=LZW -co PREDICTOR=2 -o africa/unpacked/raw.tif africa/unpacked/*.hgt.tif
 
Convert into Mercator projection, interpolate and shrink per region (raw.tif -> 90.tif)

 gdalwarp -co BIGTIFF=YES -co TILED=YES -co COMPRESS=LZW -co PREDICTOR=2 -t_srs "+proj=merc +ellps=sphere +R=6378137 +a=6378137 +units=m" -r bilinear -tr 90 90 europe/unpacked/raw.tif europe/unpacked/90.tif

 gdalwarp -co BIGTIFF=YES -co TILED=YES -co COMPRESS=LZW -co PREDICTOR=2 -t_srs "+proj=merc +ellps=sphere +R=6378137 +a=6378137 +units=m" -r bilinear -tr 90 90 africa/unpacked/raw.tif africa/unpacked/90.tif

Create 10m contour data per region (90.tif -> lon*.pbf)

 phyghtmap --step=10 --start-node-id=1000000000 --start-way-id=1000000000 --max-nodes-per-tile=0 --no-zero-contour --pbf europe/unpacked/90.tif

Wait... (4h)
  
 phyghtmap --step=10 --start-node-id=2000000000 --start-way-id=2000000000 --max-nodes-per-tile=0 --no-zero-contour --pbf africa/unpacked/90.tif
 
Wait... (2h)
 
Load contour data into contour database

 osm2pgsql -d contours --slim --cache 12000 --number-processes 10 --style ~/fcmaps/osm2pgsql/contours.style ~/data/srtm/lon*.pbf

Wait... (4h)
 
[[configure-server]]
== Configure server

=== Check server ressources

Find out database size

 psql -d postgres -c "SELECT pg_database.datname, pg_size_pretty(pg_database_size(pg_database.datname)) AS size FROM pg_database;"

gis: 190GB, contours: 80GB, lowzoom: 800MB (Germany, Austria, Switzerland, France, South Africa)
 
Display free disk space
 
 df
 
320GB used, 680GB free

SSH login with user *root*

 ssh -l root <server-dns-name>

Restart server

 sync;sync;shutdown -r now
 
Check successfully restart

 who -b
 
[[run-services]]
=== Run services

SSH login with user *gis*

Configure services as executable

 cd ~/fcmaps
 chmod +x printmaps_buildservice
 chmod +x printmaps_webservice

Start services manually
 
 nohup ./printmaps_buildservice 1>./logs/printmaps_buildservice.out 2>&1 &
 nohup ./printmaps_webservice 1>./logs/printmaps_webservice.out 2>&1 &

Test web service

 http://<server-dns-name>:8181/api/beta2/maps/capabilities/service
 
Search running service processes

 ps -Af | grep "printmaps_"
 
Terminate running service processes

 kill <pid>
 
Show log files

 cat ./logs/printmaps_buildservice.log
 cat ./logs/printmaps_webservice.log

[[install-services-autostart]]
=== Install services autostart

SSH login with user *root*

 cd /etc/systemd/system

Create service description of build service

 nano fcmaps_build.service

----
[Unit]
Description=Flight Contest maps build service
Requires=network.target
After=network.target 

[Service]
User=gis
WorkingDirectory=/home/gis/fcmaps
ExecStart=/home/gis/fcmaps/printmaps_buildservice ./printmaps_buildservice.yaml
Restart=always

[Install]
WantedBy=multi-user.target
----

Create service description of web service

 nano fcmaps_web.service
 
----
[Unit]
Description=Flight Contest maps web service
Requires=network.target
After=network.target

[Service]
User=gis
WorkingDirectory=/home/gis/fcmaps
ExecStart=/home/gis/fcmaps/printmaps_webservice ./printmaps_webservice.yaml
Restart=always

[Install]
WantedBy=multi-user.target
----

Enable autostart

 systemctl enable fcmaps_build.service
 systemctl enable fcmaps_web.service
 
Restart server

 sync;sync;shutdown -r now
 
Check successfully restart

 who -b


[[fc-configuration]]
== Configure Flight Contest

Add ```printserverapi``` in ```-> Extras -> Settings -> Config```

 flightcontest {
   contestmap {
     printserverapi = "http://<server-dns-name>:8181/api/beta2/maps"
   }
 }

and restart Flight Contest.

Test map generation with ```-> Routes -> <Route> -> OSM Contest Map```.
